### ISSUE TITLE
fix(subscription+jwt): `Error: Request is not available on context! Make sure you use this plugin with GraphQL Yoga`

### ISSUE THREAD

**Issue by jjangga0214** [graphql-hive/gateway#366]
When using a subscription, the error below happens.

```
ERROR  Error: Request is not available on context! Make sure you use this plugin with GraphQL Yoga.
```

**Stacktrace**

```sh
➜  gateway git:(main) ✗ (☸|docker-desktop:default) pnpm dev

> @passview/gateway@1.0.0 dev /Users/ocean/passview/main/packages/gateway
> pnpm ts scripts/schema.ts && concurrently 'pnpm hive-gateway supergraph' 'pnpm ts scripts/schema.ts'


> @passview/gateway@1.0.0 ts /Users/ocean/passview/main/packages/gateway
> r ts "scripts/schema.ts"

✔ Composition successful
Saving supergraph schema to supergraph.graphql
[1] 
[1] > @passview/gateway@1.0.0 ts /Users/ocean/passview/main/packages/gateway
[1] > r ts "scripts/schema.ts"
[1] 
[0] [2024-12-23T00:45:16.269Z] INFO   Found default config file /Users/ocean/passview/main/packages/gateway/gateway.config.ts 
[0] [2024-12-23T00:45:16.807Z] INFO   Loaded config 
[0] [2024-12-23T00:45:16.807Z] INFO   Using default supergraph location: supergraph.graphql 
[0] [2024-12-23T00:45:16.808Z] INFO   Reading supergraph from /Users/ocean/passview/main/packages/gateway/supergraph.graphql 
[0] [2024-12-23T00:45:16.811Z] INFO   Watching /Users/ocean/passview/main/packages/gateway/supergraph.graphql for changes 
[0] [2024-12-23T00:45:16.815Z] INFO   Serving local supergraph from /Users/ocean/passview/main/packages/gateway/supergraph.graphql 
[0] [2024-12-23T00:45:16.819Z] INFO   Listening on http://localhost:8080 
[1] ✔ Composition successful
[1] Saving supergraph schema to supergraph.graphql
[0] [2024-12-23T00:45:18.507Z] INFO   /Users/ocean/passview/main/packages/gateway/supergraph.graphql changed. Invalidating supergraph... 
[1] pnpm ts scripts/schema.ts exited with code 0
[0] [2024-12-23T00:45:46.925Z] ERROR  Error: Request is not available on context! Make sure you use this plugin with GraphQL Yoga.
[0]     at onContextBuilding (file:///Users/ocean/passview/main/node_modules/.pnpm/@graphql-yoga+plugin-jwt@3.4.6_@whatwg-node+server@0.9.64_graphql-yoga@5.10.6_graphql@16.9.0__graphql@16.9.0/node_modules/@graphql-yoga/plugin-jwt/esm/plugin.js:103:23)
[0]     at file:///Users/ocean/passview/main/node_modules/.pnpm/@envelop+core@5.0.2/node_modules/@envelop/core/esm/orchestrator.js:203:51
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async onSubscribe (file:///Users/ocean/passview/main/node_modules/.pnpm/@graphql-hive+gateway@1.7.1_@parcel+watcher@2.4.1_@types+ioredis-mock@8.2.5_@types+node@22.10_egdrufs52xwxrbw4s2e57so3aq/node_modules/@graphql-hive/gateway/dist/cli-DzxIFvUe.js:165:23)
[0]     at async onMessage (file:///Users/ocean/passview/main/node_modules/.pnpm/graphql-ws@5.16.0_graphql@16.9.0/node_modules/graphql-ws/lib/server.mjs:146:59)
[0]     at async WebSocket.<anonymous> (file:///Users/ocean/passview/main/node_modules/.pnpm/graphql-ws@5.16.0_graphql@16.9.0/node_modules/graphql-ws/lib/use/ws.mjs:80:21) 
[0] Internal error occurred during message handling. Please check your implementation. GraphQLError: Unexpected error.
[0]     at createGraphQLError (file:///Users/ocean/passview/main/node_modules/.pnpm/@graphql-tools+utils@10.6.4_graphql@16.9.0/node_modules/@graphql-tools/utils/esm/errors.js:28:12)
[0]     at maskError (file:///Users/ocean/passview/main/node_modules/.pnpm/graphql-yoga@5.10.6_graphql@16.9.0/node_modules/graphql-yoga/esm/utils/mask-error.js:30:12)
[0]     at maskError (file:///Users/ocean/passview/main/node_modules/.pnpm/graphql-yoga@5.10.6_graphql@16.9.0/node_modules/graphql-yoga/esm/server.js:82:42)
[0]     at file:///Users/ocean/passview/main/node_modules/.pnpm/@envelop+core@5.0.2/node_modules/@envelop/core/esm/plugins/use-masked-errors.js:58:26
[0]     at file:///Users/ocean/passview/main/node_modules/.pnpm/@envelop+core@5.0.2/node_modules/@envelop/core/esm/orchestrator.js:232:21
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async onSubscribe (file:///Users/ocean/passview/main/node_modules/.pnpm/@graphql-hive+gateway@1.7.1_@parcel+watcher@2.4.1_@types+ioredis-mock@8.2.5_@types+node@22.10_egdrufs52xwxrbw4s2e57so3aq/node_modules/@graphql-hive/gateway/dist/cli-DzxIFvUe.js:165:23)
[0]     at async onMessage (file:///Users/ocean/passview/main/node_modules/.pnpm/graphql-ws@5.16.0_graphql@16.9.0/node_modules/graphql-ws/lib/server.mjs:146:59)
[0]     at async WebSocket.<anonymous> (file:///Users/ocean/passview/main/node_modules/.pnpm/graphql-ws@5.16.0_graphql@16.9.0/node_modules/graphql-ws/lib/use/ws.mjs:80:21) {
[0]   path: undefined,
[0]   locations: undefined,
[0]   extensions: { unexpected: true, originalError: undefined }
[0] }
```

**gateway.config.ts**

```ts
import {
  defineConfig,
  createRemoteJwksSigningKeyProvider,
  extractFromHeader,
  type WSTransportOptions,
} from '@graphql-hive/gateway'
import { auth, config as bCoreConfig, UserRole } from '@passview/backend-core'
import config from './scripts/config.js'

export const gatewayConfig = defineConfig({
  port: config.port,
  graphiql: true,
  genericAuth: {
    mode: 'protect-granular',
    // Set where to extract the payload
    resolveUserFn: (ctx) => ctx.jwt?.payload,
    // Expected to return an array of strings
    extractScopes: (payload: auth.AccessTokenPayload) =>
      payload ? auth.getRoles(payload) : [UserRole.ANONYMOUS],
  },
  jwt: {
    singingKeyProviders: [
      createRemoteJwksSigningKeyProvider({
        jwksUri: bCoreConfig.auth.jwks.url,
      }),
    ],
    tokenLookupLocations: [
      extractFromHeader({ name: 'authorization', prefix: 'Bearer' }),
    ],
    forward: {
      token: true,
    },
    reject: {
      missingToken: false,
    },
  },
  transportEntries: {
    '*.http': {
      options: {
        subscriptions: {
          // REF: https://github.com/graphql-hive/gateway/issues/133
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-expect-error
          kind: 'ws',
          location: '/graphql',
          options: {
            connectionParams: {
              authorization: '{context.headers.authorization}',
            },
          },
        } satisfies WSTransportOptions,
      },
    },
  },
})
```

**Client code (relay)**

```tsx
const wsClient = createClient({
  url: config.api.url.ws.graphql,
  connectionParams: {
    headers: {
      authorization:
        'Bearer eyJhbGciOiJ...32H_6A', // Example
    },
  },
})

const subscribeRelay: SubscribeFunction = (operation, variables) => {
  return Observable.create((sink) => {
    return wsClient.subscribe(
      {
        operationName: operation.name,
        query: operation.text!,
        variables,
      },
      // Cast sink to the specific Sink type from graphql-ws
      sink as Sink<ExecutionResult>,
    )
  })
}
```

**Comment by enisdenjo** [comment]
The JWT plugin is not compatible with WebSockets at the moment, it needs headers from HTTP requests and WebSockets dont do HTTP requests.

**Comment by jjangga0214** [comment]
> The JWT plugin is not compatible with WebSockets at the moment, it needs headers from HTTP requests and WebSockets dont do HTTP requests.

Then how can I resolve the error?
Can I disable the jwt plugin only for subscription for example?

**Comment by dotansimha** [comment]
> The JWT plugin is not compatible with WebSockets at the moment, it needs headers from HTTP requests and WebSockets dont do HTTP requests.

To support this,  we need to extract the token from somewhere else, right? I know it's usually common to use an Upgrade request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism) to grab the auth tokens because it's the only place where headers are passed? (see https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api)

**Comment by ardatan** [comment]
- We don't handle upgrade requests in Yoga. GraphQL WS handles those.
- Connection params is where the users should provide the tokens, not HTTP headers
- We need to have a dedicated `extractFromHeaders` for the gateway that gets `headers`(which is `connectionParams` in WS)
- The error is thrown because the JWT plugin relies on a Yoga-specific hook, and GraphQL WS uses its Envelop part only. JWT plugin should be smart enough to handle stuff with Envelop hooks too.

**Comment by enisdenjo** [comment]
> To support this, we need to extract the token from somewhere else, right? I know it's usually common to use an Upgrade request 

Another point here is that browsers cannot set custom headers when connecting a WebSocket. We need to improve the JWT plugin to use the `connectionParams`, as Arda said, when running in context of WS.
